### ISSUE TITLE
TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "X-Goog-Visitor-Id"

### ISSUE THREAD

**Issue by samtaylorr** [beebls/youtube-music-history-scrobbler#2]
**Error:**
```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "X-Goog-Visitor-Id"
    at ClientRequest.setHeader (node:_http_outgoing:579:3)
    at new ClientRequest (node:_http_client:256:14)
    at Object.request (node:https:353:10)
    at RedirectableRequest._performRequest (C:\Users\itsmi\Downloads\youtube-music-history-scrobbler-main\node_modules\follow-redirects\index.js:169:24)
    at new RedirectableRequest (C:\Users\itsmi\Downloads\youtube-music-history-scrobbler-main\node_modules\follow-redirects\index.js:66:8)
    at Object.wrappedProtocol.request (C:\Users\itsmi\Downloads\youtube-music-history-scrobbler-main\node_modules\follow-redirects\index.js:307:14)
    at dispatchHttpRequest (C:\Users\itsmi\Downloads\youtube-music-history-scrobbler-main\node_modules\axios\lib\adapters\http.js:179:25)
    at new Promise (<anonymous>)
    at httpAdapter (C:\Users\itsmi\Downloads\youtube-music-history-scrobbler-main\node_modules\axios\lib\adapters\http.js:21:10)
    at dispatchRequest (C:\Users\itsmi\Downloads\youtube-music-history-scrobbler-main\node_modules\axios\lib\core\dispatchRequest.js:52:10) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
}
```

Breaks after "Api Querying items 0 to 1000"

**Comment by samtaylorr** [comment]
Similar fix was given here: https://github.com/emresenyuva/youtube-music-api/commit/b52b2b0d3fd146face64d193ba333c948e857451, after the issue was raised here: https://github.com/emresenyuva/youtube-music-api/issues/9

So I just updated that at this pull request: https://github.com/beebls/youtube-music-history-scrobbler/pull/3, feel free to close with merge if you think it helped ;)
